spring.application.name=devflow

spring.datasource.url=jdbc:mysql://localhost:3306/devflow
spring.datasource.username=haisy
spring.datasource.password=junnu1522

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
